// Package server provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package server

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for TaskResponseStatus.
const (
	COMPLITED TaskResponseStatus = "COMPLITED"
	CREATED   TaskResponseStatus = "CREATED"
	ERROR     TaskResponseStatus = "ERROR"
	STARTED   TaskResponseStatus = "STARTED"
)

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Code Error code
	Code int32 `json:"code"`

	// Message Error message
	Message string `json:"message"`
}

// TaskResponse defines model for TaskResponse.
type TaskResponse struct {
	// CompletedAt Completion date of the task solving
	CompletedAt *time.Time `json:"completedAt,omitempty"`

	// CreatedAt Task creation date
	CreatedAt time.Time `json:"createdAt"`

	// Id Task ID
	Id int64 `json:"id"`

	// Message Task solution message
	Message string `json:"message"`

	// Result Task solution result
	Result *string `json:"result,omitempty"`

	// StartedAt Start date of the task solving
	StartedAt *time.Time `json:"startedAt,omitempty"`

	// Status Task solution status
	Status TaskResponseStatus `json:"status"`
}

// TaskResponseStatus Task solution status
type TaskResponseStatus string

// PostTaskMultipartBody defines parameters for PostTask.
type PostTaskMultipartBody struct {
	File openapi_types.File `json:"file"`
}

// PostTaskParams defines parameters for PostTask.
type PostTaskParams struct {
	// Year Year of AoC challenge
	Year int32 `form:"year" json:"year"`

	// Day Puzzle day
	Day int32 `form:"day" json:"day"`

	// Part Puzzle part (1 or 2)
	Part int32 `form:"part" json:"part"`
}

// PostTaskMultipartRequestBody defines body for PostTask for multipart/form-data ContentType.
type PostTaskMultipartRequestBody PostTaskMultipartBody
