// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gofiber/fiber/v2"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Create task to solve
	// (POST /task/create)
	PostTask(c *fiber.Ctx, params PostTaskParams) error
	// Get task status
	// (GET /task/{id})
	GetTask(c *fiber.Ctx, id int64) error
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

type MiddlewareFunc fiber.Handler

// PostTask operation middleware
func (siw *ServerInterfaceWrapper) PostTask(c *fiber.Ctx) error {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params PostTaskParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Required query parameter "year" -------------

	if paramValue := c.Query("year"); paramValue != "" {

	} else {
		err = fmt.Errorf("Query argument year is required, but not found")
		c.Status(fiber.StatusBadRequest).JSON(err)
		return err
	}

	err = runtime.BindQueryParameter("form", true, true, "year", query, &params.Year)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter year: %w", err).Error())
	}

	// ------------- Required query parameter "day" -------------

	if paramValue := c.Query("day"); paramValue != "" {

	} else {
		err = fmt.Errorf("Query argument day is required, but not found")
		c.Status(fiber.StatusBadRequest).JSON(err)
		return err
	}

	err = runtime.BindQueryParameter("form", true, true, "day", query, &params.Day)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter day: %w", err).Error())
	}

	// ------------- Required query parameter "part" -------------

	if paramValue := c.Query("part"); paramValue != "" {

	} else {
		err = fmt.Errorf("Query argument part is required, but not found")
		c.Status(fiber.StatusBadRequest).JSON(err)
		return err
	}

	err = runtime.BindQueryParameter("form", true, true, "part", query, &params.Part)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter part: %w", err).Error())
	}

	return siw.Handler.PostTask(c, params)
}

// GetTask operation middleware
func (siw *ServerInterfaceWrapper) GetTask(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	return siw.Handler.GetTask(c, id)
}

// FiberServerOptions provides options for the Fiber server.
type FiberServerOptions struct {
	BaseURL     string
	Middlewares []MiddlewareFunc
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router fiber.Router, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, FiberServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router fiber.Router, si ServerInterface, options FiberServerOptions) {
	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	for _, m := range options.Middlewares {
		router.Use(fiber.Handler(m))
	}

	router.Post(options.BaseURL+"/task/create", wrapper.PostTask)

	router.Get(options.BaseURL+"/task/:id", wrapper.GetTask)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xWUXPbNgz+KzxuD+1NjimlzYPePMfX6912yTnew66XB1SCHLYSyZJQVjfn/74DpVh2",
	"YrvO1se+0QIJfPjwAfCDLGzjrEFDQeYPMhR32EA8zry3fo7BWROQPzhvHXrSGM2FLePXEkPhtSNtjcy7",
	"RyLaEolfoXE1yvytUomsrG+AZC61ofNMJpJWDrufuEQv14lsMARYHnT7aN7yLK/bb99qFDoIY0mE1jnr",
	"CcvBfSCvzVKu14n0+KXVHkuZf5A9xEeXt5v79uMnLIjRLCB8PpY/IyAsJ/Qc77QzamtECYTCVoLuUBCE",
	"zyLY+p4RbWeRqeztKE1HWbZQKldZrtRv6jxXSm7xxp5GpBt8nlwiC49wAAznIaL9Ec+x2OrlsXV5IOj7",
	"y+1I6Xma7crg4s3LZLDo+WtjJvvkcAkrkYpr8CRSUXnbiImdikxlbwQUBbq90mBlhLam7wXsb23Fu7i4",
	"2OMtEPgDtbhh03/SRPryugQCasP3supvJRJN23BrTOezyWLGpbtZTObdaXr15/Ufs+48m8+v5twxA9bh",
	"yfGu08z+JuBQwEG9zxuRfWhTWc6DNMV4k/IeDTGFU1uieLW0I/gHViMu9GuZyHv0ocs1PVNnismwDg04",
	"LXN5fqbOWHgO6C6yM+YajDsMsdFtiKXjdo9N877kSWMDMXPxpYcGCX2Q+Yen7P6N4BkZC6+4g7pGE3PU",
	"bPzSol/JRBpoOI8VgpfbFJFvMemnMEPYUMyZnTBD18lTOP2ALGF1AENnOQFC+n/iO9b9q1RYL7LXB5Dw",
	"nR8I5bZzhYF+t+Wqm9mG0MTaNm1NmgOO2dGoBIJh/z2f9pWuozQ2UT9qAxH7ccHHd/s1vUvTJRCIyvqn",
	"82CXjG5UxY0UYWVKPckLnKt1AWTN+FNgz9s5/eqxkrn8ZTws/XG/8cc7224PwJu2KDCEqq3Fpi9kvFVB",
	"Pzt/BIzdfx17cPxl8KvDgrAUyHcj5aFtGi5HLqexizsWyUYi42yEJfdqPziuKh4b8pafds3/oMs1Q1vi",
	"ns5/hyc1/rDyorh5vAzajpPvFGWftiQ7cf9UwhElvEPqm+lx3xwSwXpj2lvSBgwsseF8NuXccbG+Xf8b",
	"AAD//6JPZx1ICwAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
