// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gofiber/fiber/v2"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Create task to solve
	// (POST /task/create)
	PostTask(c *fiber.Ctx, params PostTaskParams) error
	// Get task status
	// (GET /task/{id})
	GetTask(c *fiber.Ctx, id int64) error
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

type MiddlewareFunc fiber.Handler

// PostTask operation middleware
func (siw *ServerInterfaceWrapper) PostTask(c *fiber.Ctx) error {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params PostTaskParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Required query parameter "year" -------------

	if paramValue := c.Query("year"); paramValue != "" {

	} else {
		err = fmt.Errorf("Query argument year is required, but not found")
		c.Status(fiber.StatusBadRequest).JSON(err)
		return err
	}

	err = runtime.BindQueryParameter("form", true, true, "year", query, &params.Year)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter year: %w", err).Error())
	}

	// ------------- Required query parameter "day" -------------

	if paramValue := c.Query("day"); paramValue != "" {

	} else {
		err = fmt.Errorf("Query argument day is required, but not found")
		c.Status(fiber.StatusBadRequest).JSON(err)
		return err
	}

	err = runtime.BindQueryParameter("form", true, true, "day", query, &params.Day)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter day: %w", err).Error())
	}

	// ------------- Required query parameter "part" -------------

	if paramValue := c.Query("part"); paramValue != "" {

	} else {
		err = fmt.Errorf("Query argument part is required, but not found")
		c.Status(fiber.StatusBadRequest).JSON(err)
		return err
	}

	err = runtime.BindQueryParameter("form", true, true, "part", query, &params.Part)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter part: %w", err).Error())
	}

	return siw.Handler.PostTask(c, params)
}

// GetTask operation middleware
func (siw *ServerInterfaceWrapper) GetTask(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	return siw.Handler.GetTask(c, id)
}

// FiberServerOptions provides options for the Fiber server.
type FiberServerOptions struct {
	BaseURL     string
	Middlewares []MiddlewareFunc
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router fiber.Router, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, FiberServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router fiber.Router, si ServerInterface, options FiberServerOptions) {
	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	for _, m := range options.Middlewares {
		router.Use(fiber.Handler(m))
	}

	router.Post(options.BaseURL+"/task/create", wrapper.PostTask)

	router.Get(options.BaseURL+"/task/:id", wrapper.GetTask)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xWT2/buBP9KsT8focWK8eU0uagm9cxigK7SOB4D4siB1YaOWwlkiVH2biBvvtiKMX/",
	"YqfObo97UzzkzHsz7w3zCIVtnDVoKED+CKG4w0bFz5n31s8xOGsC8g/OW4eeNMZwYcv4a4mh8NqRtgby",
	"/pKIsQTwQTWuRsjfS5lAZX2jCHLQhs4zSIBWDvs/cYkeugQaDEEtj6Z9Cm9lhuv2+/cahQ7CWBKhdc56",
	"wnKTPpDXZgldl4DHb632WEL+CQaITylv1+ft5y9YEKNZqPD1Jf6MgLCc0HO80z6orRGlIhS2EnSHglT4",
	"KoKt7xnRNotMZu9HaTrKsoWUucxyKX+R57mUsNU3zjQi3eBzcgkUHtURMMxDxPgTnpdqy9fX1uWRoh8v",
	"tyul52m2K4OLd6+TwWLoXxuZHJLDpVqJVFwrTyIVlbeNmNipyGT2TqiiQHdQGqyM0Nb0o4LDqa16FxcX",
	"B7IFUv7ILG449I80kb5+LoEUteFHrIZTCaBpG7bGdD6bLGY8upvFZN5/Ta9+v/5t1n/P5vOrOTtmg3Vz",
	"5WXXae7+uuBmgBv1Pjci59CmssyDNMV6k/IeDXELp7ZE8WZpR+ovtRrxoN9CAvfoQ881PZNnkpthHRrl",
	"NORwfibPWHhO0V3szphnMO4xRKPbEEfHdo+m+VjyprGBuHPxplcNEvoA+af97v6JyjMyFl5xp+oaTeSo",
	"OfitRb+CBIxqmMcKlYftFpFvMRm2MENYt5iZnbBDu2QfzrAgS7U6gqGPnAAh/Tf1Hev+TSqsF9nbI0j4",
	"zE+EctunwkC/2nLV72xDaOJsCR9o7GrFOB63SqzTftZGRXD7iu6SPYaXipSorN+38i6PfsvExySKLpNy",
	"D5JyrtaFImvGX4Ldw/V/jxXk8L/x5r0eD4/1eOehOgDwpi0KDKFqa7GWNMRTlRrW3s+AsfsPwwEcfxh8",
	"cFgQlgL5bFwPoW0abnQO02jAvotkYyPjWlNLttng+auKHQ+3fLX37aMuO4a2xAOm/YAneXbzWkVd8mbY",
	"yDIurVNEedr71uvyPyW8oIQPSIOZnp6KYyLo1qGDI22UUUtsmM96nDsputvu7wAAAP//2dSx/gMLAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
