// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gofiber/fiber/v2"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// PostTask Create task to solve
	// (POST /task/create)
	PostTask(c *fiber.Ctx, params PostTaskParams) error
	// GetTask Get task status
	// (GET /task/{id})
	GetTask(c *fiber.Ctx, id int64) error
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []HandlerMiddlewareFunc
}

type MiddlewareFunc fiber.Handler
type HandlerMiddlewareFunc func(c *fiber.Ctx, next fiber.Handler) error

// PostTask operation middleware
func (siw *ServerInterfaceWrapper) PostTask(c *fiber.Ctx) error {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params PostTaskParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Required query parameter "year" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "year", query, &params.Year, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter year: %w", err).Error())
	}

	// ------------- Required query parameter "day" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "day", query, &params.Day, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter day: %w", err).Error())
	}

	// ------------- Required query parameter "part" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "part", query, &params.Part, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter part: %w", err).Error())
	}

	handler := func(c *fiber.Ctx) error {
		return siw.Handler.PostTask(c, params)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c *fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// GetTask operation middleware
func (siw *ServerInterfaceWrapper) GetTask(c *fiber.Ctx) error {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	handler := func(c *fiber.Ctx) error {
		return siw.Handler.GetTask(c, id)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c *fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// FiberServerOptions provides options for the Fiber server.
type FiberServerOptions struct {
	BaseURL            string
	Middlewares        []MiddlewareFunc
	HandlerMiddlewares []HandlerMiddlewareFunc
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router fiber.Router, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, FiberServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router fiber.Router, si ServerInterface, options FiberServerOptions) {
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.HandlerMiddlewares,
	}

	for _, m := range options.Middlewares {
		router.Use(fiber.Handler(m))
	}

	router.Post(options.BaseURL+"/task/create", wrapper.PostTask)

	router.Get(options.BaseURL+"/task/:id", wrapper.GetTask)

}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7FZNc9s2EP0rmG0PyZSSQDrxgTdV1mQy0449snroZHxAyJWMhAQQYOla8fC/dxak9WXJUV0fc6O1wO57",
	"u+8t/ACFrZ01aChA/gChuMVaxc+p99bPMDhrAvIPzluHnjTGcGHL+GuJofDakbYG8u6SiLEE8F7VrkLI",
	"30uZwML6WhHkoA2dZZAArRx2f+ISPbQJ1BiCWh5N+xjeygxXzffvFQodhLEkQuOc9YTlJn0gr80S2jYB",
	"j98a7bGE/BP0EB9T3qzP289fsCBGM1fh63P8GQFhOaaneCddUFsjSkUo7ELQLQpS4asItrpjRNssMpm9",
	"H6TpIMvmUuYyy6UcSil/k2e5lLDVO842IF3jU4IJFB7VEUDMRcT4I6bn6suX1dflkcIfL7arpWdptiuH",
	"83f/TQ7zvo9NZHNIFhdqJVJxpTyJVCy8rcXYTkQms3dCFQW6gxJhhYSmoh8V7E9t1Ts/Pz+QLZDyR+Zx",
	"zaEXaSN92WwCKWrCj5j1pxJA09Rsk8lsOp5PeXzX8/Gs+5pc/nn1x7T7ns5mlzN2zwbv5srzDtQ8gXXB",
	"zRA3Kn5qSs6hzcIyD9IU643LOzTEbZzYEsWbpR2of9RqwMN+CwncoQ8d13Qoh5KbYR0a5TTkcDaUQxaf",
	"U3QbuzPiOYw6DNH0NsTxsfWjeT6WvHVsIO5cvOlVjYQ+QP5pv7t/o/KMjMVX3KqqQhM5ag5+a9CvIAGj",
	"auaxQuVhu0XkG0z6jcwQ1i1mZifs0zbZh9Mvy1KtjmDoIidASP9Pfcfaf5MK60X29ggSPvOKUG66VBjo",
	"d1uuuv1tCE2cLeE9jVylGMfDVol12s/aqAhuX9FtssfwQpESC+v37bzLo9s08WGJosuk3IOknKt0EQU3",
	"+hLsHrBfPS4gh19Gm8d71L/co51X6wDC66YoMIRFU4m1piGeWqh+970Kjt1/Hw4A+cvgvcOCsBTIZ+OC",
	"CE1dc6tzmEQLdn0kG1sZF5tastF6118u2PNww1c75z7osmVoSzxg2w94kms3b1ZUJu+GjTDj2jpFlqe9",
	"cp0yf2rhWS18QOoN9fhcHJNBuw4dHGqtjFpizYTWA91J0d60/wYAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
