// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for TaskResponseStatus.
const (
	COMPLETED TaskResponseStatus = "COMPLETED"
	CREATED   TaskResponseStatus = "CREATED"
	ERROR     TaskResponseStatus = "ERROR"
	STARTED   TaskResponseStatus = "STARTED"
)

// Valid indicates whether the value is a known member of the TaskResponseStatus enum.
func (e TaskResponseStatus) Valid() bool {
	switch e {
	case COMPLETED:
		return true
	case CREATED:
		return true
	case ERROR:
		return true
	case STARTED:
		return true
	default:
		return false
	}
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Code Error code
	//
	// Example: 500
	Code int32 `json:"code"`

	// Message Error message
	//
	// Example: Puzzle is not supported
	Message string `json:"message"`
}

// TaskResponse defines model for TaskResponse.
type TaskResponse struct {
	// CompletedAt Completion date of the task solving
	//
	// Example: 2025-11-22T00:02:00.000+03:00
	CompletedAt *time.Time `json:"completedAt,omitempty"`

	// CreatedAt Task creation date
	//
	// Example: 2025-11-22T00:00:00.000+03:00
	CreatedAt time.Time `json:"createdAt"`

	// Id Task ID
	//
	// Example: 1312
	Id int64 `json:"id"`

	// Message Task solution message
	//
	// Example: Day 1 Part 1 from AoC 2024 accepted
	Message string `json:"message"`

	// Result Task solution result
	//
	// Example: 666
	Result *string `json:"result,omitempty"`

	// StartedAt Start date of the task solving
	//
	// Example: 2025-11-22T00:01:00.000+03:00
	StartedAt *time.Time `json:"startedAt,omitempty"`

	// Status Task solution status
	//
	// Example: CREATED
	Status TaskResponseStatus `json:"status"`
}

// TaskResponseStatus Task solution status
//
// Example: CREATED
type TaskResponseStatus string

// PostTaskTextBody defines parameters for PostTask.
type PostTaskTextBody = openapi_types.File

// PostTaskParams defines parameters for PostTask.
type PostTaskParams struct {
	// Year Year of AoC challenge
	Year int32 `form:"year" json:"year"`

	// Day Puzzle day
	Day int32 `form:"day" json:"day"`

	// Part Puzzle part (1 or 2)
	Part int32 `form:"part" json:"part"`
}

// PostTaskTextRequestBody defines body for PostTask for text/plain ContentType.
type PostTaskTextRequestBody = PostTaskTextBody
